src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 *
 */
class Product
{
    /**
     * @Groups("normal")
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups("normal")
     * @ORM\Column(type="integer", nullable=true)
     */
    private $code;

    /**
     * @Groups("normal")
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @Groups("normal")
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @Groups("normal")
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit;

    /**
     * @ORM\OneToMany(targetEntity=DetailEntry::class, mappedBy="product")
     */
    private $detailEntries;

    /**
     * @ORM\OneToMany(targetEntity=DetalleSalida::class, mappedBy="product")
     */
    private $detalleSalidas;

    /**
     * @ORM\ManyToOne(targetEntity=Medida::class, inversedBy="products")
     */
    private $medida;

    public function __construct()
    {
        $this->detailEntries = new ArrayCollection();
        $this->detalleSalidas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPriceUnit(): ?string
    {
        return $this->price_unit;
    }

    public function setPriceUnit(string $price_unit): self
    {
        $this->price_unit = $price_unit;

        return $this;
    }

    /**
     * @return Collection|DetailEntry[]
     */
    public function getDetailEntries(): Collection
    {
        return $this->detailEntries;
    }

    public function addDetailEntry(DetailEntry $detailEntry): self
    {
        if (!$this->detailEntries->contains($detailEntry)) {
            $this->detailEntries[] = $detailEntry;
            $detailEntry->setProduct($this);
        }

        return $this;
    }

    public function removeDetailEntry(DetailEntry $detailEntry): self
    {
        if ($this->detailEntries->contains($detailEntry)) {
            $this->detailEntries->removeElement($detailEntry);
            // set the owning side to null (unless already changed)
            if ($detailEntry->getProduct() === $this) {
                $detailEntry->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DetalleSalida[]
     */
    public function getDetalleSalidas(): Collection
    {
        return $this->detalleSalidas;
    }

    public function addDetalleSalida(DetalleSalida $detalleSalida): self
    {
        if (!$this->detalleSalidas->contains($detalleSalida)) {
            $this->detalleSalidas[] = $detalleSalida;
            $detalleSalida->setProduct($this);
        }

        return $this;
    }

    public function removeDetalleSalida(DetalleSalida $detalleSalida): self
    {
        if ($this->detalleSalidas->contains($detalleSalida)) {
            $this->detalleSalidas->removeElement($detalleSalida);
            // set the owning side to null (unless already changed)
            if ($detalleSalida->getProduct() === $this) {
                $detalleSalida->setProduct(null);
            }
        }

        return $this;
    }

    public function getMedida(): ?Medida
    {
        return $this->medida;
    }

    public function setMedida(?Medida $medida): self
    {
        $this->medida = $medida;

        return $this;
    }
}

templates/pdf/pdf.html.twig
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reportes</title>
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }

        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
<h3>Reporte de salidas y entradas de :
    {% if fecha !='' %}
        {{ fecha }}
    {% elseif fechaentre != '' %}
        {{ fechaentre }}
    {% endif %}
</h3>
<h5 class="card-title">Salidas: </h5>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th>O/C</th>
            <th>Descripción</th>
            <th>Unidad</th>
            <th>Precio Unit.</th>
            <th>Cantidad</th>
            <th>Fecha</th>
            <th>Origen</th>
            <th>Valorizacion</th>
            <th>Firma</th>
        </tr>
        {% set totalF = 0.0 %}
        {% for s in salidas %}
            {% for d  in s.detalleSalidas %}
                <tr>
                    <td>{{ d.product.code }}</td>
                    <td>{{ d.product.description }}</td>
                    <td>{{ d.product.medida.abreviacion }}</td>
                    <td>{{ d.product.priceUnit }}</td>
                    <td>{{ d.quantity }}</td>
                    <td>{{ s.date ? s.date|date('d/m/Y H:i:s') : '' }}</td>
                    <td>{{ s.name }}</td>
                    <td>S/. {{ (d.product.priceUnit * d.quantity)|number_format(2, '.') }}</td>
                    <td width="100"></td>
                </tr>
            {% endfor %}
            {% set totalF = s.total + totalF %}
        {% endfor %}

        <tr>
            <td style="text-align: end" colspan="7">Total de Salidas</td>
            <td class="font-weight-bold bg-warning">S/. {{ totalF|number_format(2, '.') }}</td>
        </tr>
    </table>
</div>

<h5 class="card-title">Entradas: </h5>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th>O/C</th>
            <th>Descripción</th>
            <th>Unidad</th>
            <th>Precio Unit.</th>
            <th>Cantidad</th>
            <th>Fecha</th>
            <th>Destino</th>
            <th>Valorizacion</th>
            <th>Firma</th>
        </tr>
        {% set totalFE = 0.0 %}
        {% for s in entradas %}
            {% for d  in s.detailEntries %}
                <tr>
                    <td>{{ d.product.code }}</td>
                    <td>{{ d.product.description }}</td>
                    <td>{{ d.product.medida.abreviacion }}</td>
                    <td>{{ d.product.priceUnit }}</td>
                    <td>{{ d.quantity }}</td>
                    <td>{{ s.date ? s.date|date('d/m/Y H:i:s') : '' }}</td>
                    <td>{{ s.name }}</td>
                    <td>S/.{{ (d.product.priceUnit * d.quantity)|number_format(2, '.') }}</td>
                    <td width="100"></td>
                </tr>
            {% endfor %}
            {% set totalFE = s.total + totalFE %}
        {% endfor %}

        <tr>
            <td style="text-align: end" colspan="7">Total de Salidas</td>
            <td class="font-weight-bold bg-warning">S/. {{ totalFE|number_format(2, '.') }}</td>
        </tr>
    </table>
</div>

</body>
</html>